version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=contactdb
      - DB_USER=admin
      - DB_PASS=geheim

  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootwachtwoord
      MYSQL_DATABASE: contactdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: geheim
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  db_data: